---
title: "Contact"
---


### Office Hours

Any GW student is welcome at my office hours.  This schedule is up to date:

<div style="max-width: 75%; margin-left: 2rem">
Day  | Time
-----|------
Tues | 11:30 AM - 1:00 PM
Weds | 3:30 PM - 5:45 PM
Fri  | 1 PM - 4 PM
</div>

You are welcome to make an [appointment](https://calendar.app.google/QGPPEVvdwnbuEnzM9). Appointments are not necessary, but will receive priority if you send an agenda in advance.

My office can be slightly difficult to find:

- It is on SEH 4th Floor, West wing
    - Exiting the elevators, make a right
    - From the top of the stairs, go straight
- Go through the glass door (your card will work)
- Make a right where a right can be made, then an immediate left
- My office, SEH 4675, will be on the left

### Electronic Mail

My address is [joe.goldfrank@gwu.edu](mailto:joe.goldfrank@gwu.edu). My notes are typically short, direct, and polite; I encourage you to write to me in this way.<br/>

Lately there is a trend towards long formal notes, perhaps generated with some algorithm. This style makes it harder for me to find your message amidst all the words.


*Please refrain from sending me sales/marketing materials, I will mark these as spam.*